FROM jekyll/jekyll:pages

RUN gem install jekyll-redirect-from
RUN gem install jekyll-paginate
RUN gem install susy
RUN gem install normalize-scss
RUN gem install compass
RUN gem install sass
RUN gem install support-for

ENTRYPOINT [ "jekyll" ]
